services:
  database:
    image: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data    
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: demo_frame_editor
    ports:
      - "5432:5432"